title: Daemon-Technologies Documentation
description: Can't be evil

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Gemfile
  - Gemfile.lock
